### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by sjempotje** [devnote-dev/dashactyl.py#1]
Hi, 

I got this error in my terminal:
`ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sem20\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sem20\\AppData\\Local\\Temp\\pip-req-build-tkvray4h\\setup.py'"'"'; __file__='"'"'C:\\Users\\sem20\\AppData\\Local\\Temp\\pip-req-build-tkvray4h\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sem20\AppData\Local\Temp\pip-pip-egg-info-1ruvoic4'
         cwd: C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\setup.py", line 2, in <module>
        from dashactylpy import __version__
      File "C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\dashactylpy\__init__.py", line 14, in <module>
        from .api import *
      File "C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\dashactylpy\api.py", line 4, in <module>
        from .managers import DashServerManager, DashUserManager, CouponManager
      File "C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\dashactylpy\managers.py", line 1, in <module>
        from .api import Dashactyl
    ImportError: cannot import name 'Dashactyl' from partially initialized module 'dashactylpy.api' (most likely due to a circular import) (C:\Users\sem20\AppData\Local\Temp\pip-req-build-tkvray4h\dashactylpy\api.py)`

I don't know how to fix it, could you help me?
-  Sjempotje

**Comment by devnote-dev** [comment]
I will look into it soon, but a large part of the repository is slightly outdated due to the many restructures the dashactyl API has had. Everything will be updated properly when official news regarding the API is released.

**Comment by devnote-dev** [comment]
Update on this: it seems to be a issue with the package entirely, a proper rewrite is needed however, Dashactyl v0.4 (which this package was originally designed for) has been deprecated and the v1 API is almost completely different from previous versions. I will discuss potential changes with the Votion team soon.

**Comment by AndyIsHereBoi** [comment]
is there any updates on this?
